const swaggerJsdoc = require('swagger-jsdoc');
const options = {
  // List of files to be processed.
  apis: ['./routes/index.js', './routes/users.js'],
  // You can also set globs for your apis
  // e.g. './routes/*.js'
  basePath: '/',
  swaggerDefinition: {
    info: {
      description: 'Test API with autogenerated swagger doc',
      swagger: '2.0',
      title: 'Dessert API',
      version: '1.0.0',
    },
  },
};
const specs = swaggerJsdoc(options);
export default specs;